import ComplexCSP.Algebra.WorkingField
import ComplexCSP.Algebra.IntegralPrimitivePresentation
import ComplexCSP.Algebra.EncodedNumberField
import ComplexCSP.Structure.PolynomialPrograms
import Mathlib.FieldTheory.IntermediateField.Adjoin.Algebra

/-!
# Exact primitive presentations of finite algebraic input families

These are existence and coverage proofs for initial-input enumeration. They
construct polynomial-program witnesses from the actual generated field rather
than assuming a primitive expression or input coordinate witnesses.
-/
namespace ComplexCSP.AlgebraicEncoding

open Polynomial IntermediateField
open scoped BigOperators

/-- Every member of a finitely generated polynomial subalgebra has a literal,
finite executable sparse polynomial program in those generators. -/
theorem exists_program_of_mem_adjoin
    {R : Type*} [CommSemiring R] [Algebra ℚ R] {m : ℕ}
    (x : Fin m → R) {z : R} (hz : z ∈ Algebra.adjoin ℚ (Set.range x)) :
    ∃ P : PolynomialPrograms.Program ℚ m,
      PolynomialPrograms.interpret (algebraMap ℚ R) x P = z := by
  refine Algebra.adjoin_induction ?_ ?_ ?_ ?_ hz
  · rintro y ⟨i, rfl⟩
    exact ⟨PolynomialPrograms.coordinate i, PolynomialPrograms.interpret_variable _ _ _⟩
  · intro q
    exact ⟨PolynomialPrograms.constant q, PolynomialPrograms.interpret_constant _ _ _⟩
  · rintro a b _ _ ⟨P, hP⟩ ⟨Q, hQ⟩
    exact ⟨PolynomialPrograms.add P Q, by rw [PolynomialPrograms.interpret_add, hP, hQ]⟩
  · rintro a b _ _ ⟨P, hP⟩ ⟨Q, hQ⟩
    exact ⟨PolynomialPrograms.multiply P Q, by rw [PolynomialPrograms.interpret_multiply, hP, hQ]⟩

/-- The exact field generated by the finite complex input vector. -/
noncomputable def initialInputField {m : ℕ} (x : Fin m → ℂ) : IntermediateField ℚ ℂ :=
  IntermediateField.adjoin ℚ (Set.range x)

theorem initialInputField_numberField {m : ℕ} (x : Fin m → ℂ)
    (hx : ∀ i, IsAlgebraic ℚ (x i)) : NumberField (initialInputField x) := by
  letI : Finite (Set.range x) := (Set.finite_range x).to_subtype
  letI : FiniteDimensional ℚ (initialInputField x) :=
    IntermediateField.finiteDimensional_adjoin (by rintro z ⟨i, rfl⟩; exact (hx i).isIntegral)
  exact ⟨⟩

theorem input_mem_initialInputField {m : ℕ} (x : Fin m → ℂ) (i : Fin m) :
    x i ∈ initialInputField x := IntermediateField.subset_adjoin ℚ _ ⟨i, rfl⟩

/-- Algebraicity removes all denominators inside the generated field. -/
theorem exists_program_of_mem_initialInputField {m : ℕ} (x : Fin m → ℂ)
    (hx : ∀ i, IsAlgebraic ℚ (x i)) {z : ℂ} (hz : z ∈ initialInputField x) :
    ∃ P : PolynomialPrograms.Program ℚ m,
      PolynomialPrograms.interpret (algebraMap ℚ ℂ) x P = z := by
  apply exists_program_of_mem_adjoin x
  have he := IntermediateField.adjoin_algebraic_toSubalgebra
    (F := ℚ) (S := Set.range x) (by rintro z ⟨i, rfl⟩; exact hx i)
  change z ∈ (initialInputField x).toSubalgebra at hz
  rwa [initialInputField, he] at hz

/-- Integral primitive presentation, rational coordinates for every input, and
an actual polynomial-program expression for its generator, all proved to exist. -/
theorem exists_initial_primitive_coordinates {m : ℕ} (x : Fin m → ℂ)
    (hx : ∀ i, IsAlgebraic ℚ (x i)) :
    letI := initialInputField_numberField x hx
    ∃ (P : IntegralPrimitivePresentation (initialInputField x))
      (coordinates : Fin m → EncodedNumberField.CoeffVector P.basis.dim)
      (expression : PolynomialPrograms.Program ℚ m),
      (∀ i, EncodedNumberField.interpret (P.basis.gen : ℂ) (coordinates i) = x i) ∧
      PolynomialPrograms.interpret (algebraMap ℚ ℂ) x expression = (P.basis.gen : ℂ) := by
  letI := initialInputField_numberField x hx
  obtain ⟨P⟩ := exists_integralPrimitivePresentation (K := initialInputField x)
  let value (i : Fin m) : initialInputField x := ⟨x i, input_mem_initialInputField x i⟩
  let coordinates i := P.basis.basis.equivFun (value i)
  obtain ⟨expression, he⟩ := exists_program_of_mem_initialInputField x hx P.basis.gen.property
  refine ⟨P, coordinates, expression, ?_, he⟩
  intro i
  have h := congrArg (algebraMap (initialInputField x) ℂ)
    (EncodedNumberField.interpret_coordinates P.basis (value i))
  simpa only [EncodedNumberField.interpret, map_sum, map_mul, map_pow,
    ← IsScalarTower.algebraMap_apply ℚ (initialInputField x) ℂ] using h

/-- Renaming the variables by an input/conjugate swap computes conjugation of
any rational polynomial expression. -/
theorem program_conjugate_by_input_swap {m : ℕ} (x : Fin m → ℂ)
    (swap : Fin m → Fin m) (hswap : ∀ i, x (swap i) = star (x i))
    (P : PolynomialPrograms.Program ℚ m) :
    PolynomialPrograms.interpret (algebraMap ℚ ℂ) x (PolynomialPrograms.rename P swap) =
      star (PolynomialPrograms.interpret (algebraMap ℚ ℂ) x P) := by
  rw [PolynomialPrograms.interpret_rename]
  have h := PolynomialPrograms.map_interpret (algebraMap ℚ ℂ) (starRingEnd ℂ) x P
  have hc : (starRingEnd ℂ).comp (algebraMap ℚ ℂ) = algebraMap ℚ ℂ := by
    ext q
    simp
  rw [hc] at h
  have he : x ∘ swap = fun i => (starRingEnd ℂ) (x i) := funext hswap
  rw [he]
  exact h.symm

/-- A program always denotes an element of the polynomial subalgebra generated
by its actual inputs. -/
theorem program_interpret_mem_adjoin {R : Type*} [CommSemiring R] [Algebra ℚ R]
    {m : ℕ} (x : Fin m → R) (P : PolynomialPrograms.Program ℚ m) :
    PolynomialPrograms.interpret (algebraMap ℚ R) x P ∈ Algebra.adjoin ℚ (Set.range x) := by
  rw [PolynomialPrograms.interpret_eq_indexed_sum]
  apply (Algebra.adjoin ℚ (Set.range x)).sum_mem
  intro i _
  apply mul_mem ((Algebra.adjoin ℚ (Set.range x)).algebraMap_mem _)
  apply (Algebra.adjoin ℚ (Set.range x)).prod_mem
  intro j _
  exact (Algebra.adjoin ℚ (Set.range x)).pow_mem (Algebra.subset_adjoin ⟨j, rfl⟩) _

/-- The two finite witness families certify exactness: coordinates put all
inputs in Q(α), while the program puts α in the input-generated field. -/
theorem exact_field_of_coordinate_and_program_witnesses {m n : ℕ}
    (x : Fin m → ℂ) (α : ℂ) (coordinates : Fin m → EncodedNumberField.CoeffVector n)
    (hc : ∀ i, EncodedNumberField.interpret α (coordinates i) = x i)
    (P : PolynomialPrograms.Program ℚ m)
    (hP : PolynomialPrograms.interpret (algebraMap ℚ ℂ) x P = α) :
    initialInputField x = ℚ⟮α⟯ := by
  apply le_antisymm
  · apply IntermediateField.adjoin_le_iff.mpr
    rintro y ⟨i, rfl⟩
    rw [← hc i]
    apply ℚ⟮α⟯.sum_mem
    intro j _
    exact mul_mem (ℚ⟮α⟯.algebraMap_mem _) (pow_mem (mem_adjoin_simple_self ℚ α) _)
  · apply IntermediateField.adjoin_simple_le_iff.mpr
    rw [← hP]
    exact IntermediateField.algebra_adjoin_le_adjoin ℚ (Set.range x)
      (program_interpret_mem_adjoin x P)

/-- The actual finite vector with originals followed by their conjugates. -/
def pairedInputs {n : ℕ} (z : Fin n → ℂ) (i : Fin (n + n)) : ℂ :=
  Sum.elim z (fun j => star (z j)) (finSumFinEquiv.symm i)

/-- Executable index swap between the two halves. -/
def pairedInputSwap {n : ℕ} (i : Fin (n + n)) : Fin (n + n) :=
  finSumFinEquiv (Sum.swap (finSumFinEquiv.symm i))

 theorem pairedInputs_left {n : ℕ} (z : Fin n → ℂ) (i : Fin n) :
    pairedInputs z (finSumFinEquiv (Sum.inl i)) = z i := by
  simp only [pairedInputs, Equiv.symm_apply_apply, Sum.elim_inl]

 theorem pairedInputs_right {n : ℕ} (z : Fin n → ℂ) (i : Fin n) :
    pairedInputs z (finSumFinEquiv (Sum.inr i)) = star (z i) := by
  simp only [pairedInputs, Equiv.symm_apply_apply, Sum.elim_inr]

 theorem pairedInputSwap_involutive {n : ℕ} :
    Function.Involutive (pairedInputSwap (n := n)) := by
  intro i
  simp [pairedInputSwap]

 theorem pairedInputs_swap {n : ℕ} (z : Fin n → ℂ) (i : Fin (n + n)) :
    pairedInputs z (pairedInputSwap i) = star (pairedInputs z i) := by
  obtain ⟨j, rfl⟩ := finSumFinEquiv.surjective i
  cases j <;> simp only [pairedInputs, pairedInputSwap, Equiv.symm_apply_apply,
    Sum.swap_inl, Sum.swap_inr, Sum.elim_inl, Sum.elim_inr, star_star]

 theorem pairedInputs_algebraic {n : ℕ} (z : Fin n → ℂ)
    (hz : ∀ i, IsAlgebraic ℚ (z i)) : ∀ i, IsAlgebraic ℚ (pairedInputs z i) := by
  intro i
  obtain ⟨j, rfl⟩ := finSumFinEquiv.surjective i
  cases j with
  | inl j => simpa only [pairedInputs, Equiv.symm_apply_apply, Sum.elim_inl] using hz j
  | inr j =>
    simpa only [pairedInputs, Equiv.symm_apply_apply, Sum.elim_inr] using
      (IsIntegral.map (Complex.conjAe.restrictScalars ℚ) (hz j).isIntegral).isAlgebraic

/-- Coverage for every finite family of actual algebraic complex values,
including literal polynomial witnesses for both primitive generator and conjugate. -/
theorem exists_initial_conjugate_primitive_coordinates {n : ℕ} (z : Fin n → ℂ)
    (hz : ∀ i, IsAlgebraic ℚ (z i)) :
    letI := initialInputField_numberField (pairedInputs z) (pairedInputs_algebraic z hz)
    ∃ (P : IntegralPrimitivePresentation (initialInputField (pairedInputs z)))
      (coordinates : Fin (n + n) → EncodedNumberField.CoeffVector P.basis.dim)
      (expression : PolynomialPrograms.Program ℚ (n + n)),
      (∀ i, EncodedNumberField.interpret (P.basis.gen : ℂ) (coordinates i) = pairedInputs z i) ∧
      PolynomialPrograms.interpret (algebraMap ℚ ℂ) (pairedInputs z) expression = (P.basis.gen : ℂ) ∧
      PolynomialPrograms.interpret (algebraMap ℚ ℂ) (pairedInputs z)
        (PolynomialPrograms.rename expression pairedInputSwap) = star (P.basis.gen : ℂ) := by
  letI := initialInputField_numberField (pairedInputs z) (pairedInputs_algebraic z hz)
  obtain ⟨P, coordinates, expression, hc, he⟩ :=
    exists_initial_primitive_coordinates (pairedInputs z) (pairedInputs_algebraic z hz)
  exact ⟨P, coordinates, expression, hc, he, by
    rw [program_conjugate_by_input_swap _ _ (pairedInputs_swap z), he]⟩

section Language
variable {D ι : Type} [Fintype D] [Fintype ι]

abbrev LanguageInputIndex (L : Language D ℂ ι) :=
  (Σ i, Fin (L.arity i) → D) × Bool

/-- A proof-level enumeration of precisely the input entries and their conjugates. -/
noncomputable def languageInputVector (L : Language D ℂ ι) :
    Fin (Fintype.card (LanguageInputIndex L)) → ℂ := fun i =>
  let p := (Fintype.equivFin (LanguageInputIndex L)).symm i
  if p.2 then star (L.value p.1.1 p.1.2) else L.value p.1.1 p.1.2

 theorem languageInputVector_range (L : Language D ℂ ι) :
    Set.range (languageInputVector L) = L.conjugateValues := by
  ext z
  constructor
  · rintro ⟨i, rfl⟩
    exact ⟨(Fintype.equivFin (LanguageInputIndex L)).symm i, rfl⟩
  · rintro ⟨p, rfl⟩
    refine ⟨Fintype.equivFin (LanguageInputIndex L) p, ?_⟩
    change (fun q : LanguageInputIndex L =>
      if q.2 then star (L.value q.1.1 q.1.2) else L.value q.1.1 q.1.2)
        ((Fintype.equivFin (LanguageInputIndex L)).symm
          (Fintype.equivFin (LanguageInputIndex L) p)) = _
    rw [Equiv.symm_apply_apply]

 theorem languageInputVector_field (L : Language D ℂ ι) :
    initialInputField (languageInputVector L) = L.workingField := by
  simp only [initialInputField, languageInputVector_range, Language.workingField]

 theorem languageInputVector_algebraic (L : Language D ℂ ι)
    (hL : ∀ i a, IsAlgebraic ℚ (L.value i a)) :
    ∀ i, IsAlgebraic ℚ (languageInputVector L i) := by
  intro i
  apply (L.conjugateValues_integral hL _ _).isAlgebraic
  rw [← languageInputVector_range]
  exact ⟨i, rfl⟩

/-- Index involution pairing each language entry with its actual conjugate. -/
noncomputable def languageInputSwap (L : Language D ℂ ι)
    (i : Fin (Fintype.card (LanguageInputIndex L))) : Fin (Fintype.card (LanguageInputIndex L)) :=
  let p := (Fintype.equivFin (LanguageInputIndex L)).symm i
  Fintype.equivFin (LanguageInputIndex L) (p.1, !p.2)

 theorem languageInputVector_swap (L : Language D ℂ ι)
    (i : Fin (Fintype.card (LanguageInputIndex L))) :
    languageInputVector L (languageInputSwap L i) = star (languageInputVector L i) := by
  let value (p : LanguageInputIndex L) :=
    if p.2 then star (L.value p.1.1 p.1.2) else L.value p.1.1 p.1.2
  let e := Fintype.equivFin (LanguageInputIndex L)
  obtain ⟨p, rfl⟩ := e.surjective i
  change value (e.symm (e (((e.symm (e p)).1), !(e.symm (e p)).2))) = star (value (e.symm (e p)))
  rw [e.symm_apply_apply, e.symm_apply_apply]
  rcases p with ⟨p, b⟩
  cases b <;> simp [value]

/-- The existing Section 4 working field itself admits all finite witnesses;
this is the same exact field, rather than an unspecified ambient extension. -/
theorem exists_workingField_primitive_coordinates (L : Language D ℂ ι)
    (hL : ∀ i a, IsAlgebraic ℚ (L.value i a)) :
    letI := L.workingField_numberField hL
    ∃ (P : IntegralPrimitivePresentation L.workingField)
      (coordinates : Fin (Fintype.card (LanguageInputIndex L)) →
        EncodedNumberField.CoeffVector P.basis.dim)
      (expression : PolynomialPrograms.Program ℚ (Fintype.card (LanguageInputIndex L))),
      (∀ i, EncodedNumberField.interpret (P.basis.gen : ℂ) (coordinates i) = languageInputVector L i) ∧
      PolynomialPrograms.interpret (algebraMap ℚ ℂ) (languageInputVector L) expression =
        (P.basis.gen : ℂ) := by
  letI := L.workingField_numberField hL
  obtain ⟨P⟩ := exists_integralPrimitivePresentation (K := L.workingField)
  have hmem (i) : languageInputVector L i ∈ L.workingField := by
    rw [← languageInputVector_field]
    exact input_mem_initialInputField _ i
  let value (i) : L.workingField := ⟨languageInputVector L i, hmem i⟩
  let coordinates i := P.basis.basis.equivFun (value i)
  have hg : (P.basis.gen : ℂ) ∈ initialInputField (languageInputVector L) := by
    rw [languageInputVector_field]
    exact P.basis.gen.property
  obtain ⟨expression, he⟩ := exists_program_of_mem_initialInputField
    (languageInputVector L) (languageInputVector_algebraic L hL) hg
  refine ⟨P, coordinates, expression, ?_, he⟩
  intro i
  have h := congrArg (algebraMap L.workingField ℂ)
    (EncodedNumberField.interpret_coordinates P.basis (value i))
  simpa only [EncodedNumberField.interpret, map_sum, map_mul, map_pow,
    ← IsScalarTower.algebraMap_apply ℚ L.workingField ℂ] using h

/-- The language enumeration also has a finite swapped expression for the
conjugate primitive generator of its exact Section 4 working field. -/
theorem exists_workingField_conjugate_primitive_coordinates (L : Language D ℂ ι)
    (hL : ∀ i a, IsAlgebraic ℚ (L.value i a)) :
    letI := L.workingField_numberField hL
    ∃ (P : IntegralPrimitivePresentation L.workingField)
      (coordinates : Fin (Fintype.card (LanguageInputIndex L)) →
        EncodedNumberField.CoeffVector P.basis.dim)
      (expression : PolynomialPrograms.Program ℚ (Fintype.card (LanguageInputIndex L))),
      (∀ i, EncodedNumberField.interpret (P.basis.gen : ℂ) (coordinates i) = languageInputVector L i) ∧
      PolynomialPrograms.interpret (algebraMap ℚ ℂ) (languageInputVector L) expression =
        (P.basis.gen : ℂ) ∧
      PolynomialPrograms.interpret (algebraMap ℚ ℂ) (languageInputVector L)
        (PolynomialPrograms.rename expression (languageInputSwap L)) = star (P.basis.gen : ℂ) := by
  letI := L.workingField_numberField hL
  obtain ⟨P, coordinates, expression, hc, he⟩ := exists_workingField_primitive_coordinates L hL
  exact ⟨P, coordinates, expression, hc, he, by
    rw [program_conjugate_by_input_swap _ _ (languageInputVector_swap L), he]⟩

end Language
end ComplexCSP.AlgebraicEncoding
