import ComplexCSP.Algebra.LegalPurificationChoices

/-!
# Existence of exact legal data and changes of ambient family

The quotient-basis construction yields generators inside the group generated by
the finite values, hence inside their field. The resulting data satisfy every
field of LegalGeneratingSet. Arbitrary legal data can then be restricted from
different ambient entry groups to a common intrinsic subgroup.
-/
namespace ComplexCSP.GeneratingSet

open Purification
open scoped BigOperators

namespace LegalGeneratingSet

noncomputable def fieldUnits (S : Finset ℂˣ) : Subgroup ℂˣ where
  carrier := {u | (u : ℂ) ∈ fieldOfValues S}
  one_mem' := (fieldOfValues S).one_mem
  mul_mem' := fun ha hb => (fieldOfValues S).mul_mem ha hb
  inv_mem' := by
    intro u hu
    change ((u⁻¹ : ℂˣ) : ℂ) ∈ fieldOfValues S
    simpa only [Units.val_inv_eq_inv_val] using (fieldOfValues S).inv_mem hu

theorem entryGroup_le_fieldUnits (S : Finset ℂˣ) : EntryGroup S ≤ fieldUnits S := by
  apply (Subgroup.closure_le _).mpr
  intro u hu
  exact Subfield.subset_closure ⟨u, hu, rfl⟩

/-- The canonical torsion-free quotient basis satisfies the exact legal record,
including field membership and all integer-exponent conditions. -/
theorem nonempty (S : Finset ℂˣ) : Nonempty (LegalGeneratingSet S) := by
  classical
  let H := EntryGroup S
  let c := chooseCoordinates H
  let asH : S → H := fun a => ⟨a.val, Subgroup.subset_closure a.property⟩
  refine ⟨{
    rank := c.rank
    generators := fun i => (c.generator i).val
    generators_in_field := fun i => entryGroup_le_fieldUnits S (c.generator i).property
    independent := ?_
    exponents := fun a => c.exponent (Additive.ofMul (asH a))
    remainder_torsion := ?_
  }⟩
  · intro k hk
    apply (c.generator_independence k).mp
    apply H.subtype_injective.isOfFinOrder_iff.mp
    simpa only [map_prod, map_zpow, Subgroup.subtype_apply] using hk
  · intro a
    have he := congrArg H.subtype (c.generator_decomposition (asH a))
    simp only [map_mul, map_prod, map_zpow, Subgroup.subtype_apply] at he
    have hr : a.val / (∏ i, (c.generator i).val ^ c.exponent (Additive.ofMul (asH a)) i) =
        (Additive.toMul (c.phaseAdd (Additive.ofMul (asH a)))).val := by
      change (asH a).val / _ = _
      rw [he]
      simp
    rw [hr]
    exact H.subtype.isOfFinOrder (c.phaseAdd_finite_order (asH a))

noncomputable def choose (S : Finset ℂˣ) : LegalGeneratingSet S := Classical.choice (nonempty S)

/-- Restrict an arbitrary legal ambient map to any subgroup of its entry group. -/
noncomputable def restrictMap {S : Finset ℂˣ} (L : LegalGeneratingSet S)
    (H : Subgroup ℂˣ) (hH : H ≤ EntryGroup S) : PurificationMap H H.subtype where
  hom := L.purifiedHom.comp (Subgroup.inclusion hH)
  injective := L.purifiedHom_injective.comp (by
    intro x y h
    exact Subtype.ext (congrArg (fun z : EntryGroup S => z.val) h))
  fixes_torsion := by
    intro x hx
    exact L.purifiedHom_torsion ((Subgroup.inclusion hH).isOfFinOrder hx)
  norm_one_iff := by
    intro x
    exact (L.purifiedHom_norm_one_iff _).trans
      (show IsOfFinOrder (Subgroup.inclusion hH x) ↔ IsOfFinOrder x from
        (show Function.Injective (Subgroup.inclusion hH) from fun x y h =>
          Subtype.ext (congrArg (fun z : EntryGroup S => z.val) h)).isOfFinOrder_iff)

/-- Ambient invariance for two arbitrary legal generating choices, even when
their ambient sets and exponent ranks differ. -/
theorem ambient_blockOrthogonal_iff {S T : Finset ℂˣ}
    (L : LegalGeneratingSet S) (M : LegalGeneratingSet T)
    (H : Subgroup ℂˣ) (hHS : H ≤ EntryGroup S) (hHT : H ≤ EntryGroup T)
    {X D : Type*} [Fintype D] (A : X → D → Option H) :
    BlockOrthogonality.BlockOrthogonal (fun x => (L.restrictMap H hHS).entry ∘ A x) ↔
      BlockOrthogonality.BlockOrthogonal (fun x => (M.restrictMap H hHT).entry ∘ A x) :=
  (L.restrictMap H hHS).blockOrthogonal_iff (M.restrictMap H hHT) A

/-- The same arbitrary-choice theorem with positive table normalizations. -/
theorem normalized_ambient_blockOrthogonal_iff {S T : Finset ℂˣ}
    (L : LegalGeneratingSet S) (M : LegalGeneratingSet T)
    (H : Subgroup ℂˣ) (hHS : H ≤ EntryGroup S) (hHT : H ≤ EntryGroup T)
    {X D : Type*} [Fintype D] (A : X → D → Option H)
    {N K : ℝ} (hN : 0 < N) (hK : 0 < K) :
    BlockOrthogonality.BlockOrthogonal
        (fun x z => (N : ℂ) * (L.restrictMap H hHS).entry (A x z)) ↔
      BlockOrthogonality.BlockOrthogonal
        (fun x z => (K : ℂ) * (M.restrictMap H hHT).entry (A x z)) :=
  (L.restrictMap H hHS).normalized_blockOrthogonal_iff (M.restrictMap H hHT) A hN hK

end LegalGeneratingSet
end ComplexCSP.GeneratingSet
