import ComplexCSP.Instances.Basic
import Mathlib.Data.Fintype.Card

/-! # Two-row external arity compression

The constructive finite-instance part of Lemma 3.4. Instead of discarding
unused ordered pairs, we retain isolated boundary variables for all of `D × D`.
This gives the same upper bound `|D|² + 1`, with an especially direct map.
This file does not assume or assert the purification-invariance step.
-/
namespace ComplexCSP

variable {D K ι B : Type} {L : Language D K ι}

/-- A table row, with its last variable kept separate from every row coordinate. -/
def row (G : (B ⊕ Unit → D) → K) (x : B → D) (z : D) : K :=
  G (Sum.elim x (fun _ => z))

/-- Merge row positions having the same ordered pair of witness values;
the last coordinate is never merged with a row coordinate. -/
def pairCompressionMap (x y : B → D) : B ⊕ Unit → (D × D) ⊕ Unit :=
  Sum.map (fun i => (x i, y i)) id

/-- The literal diagonal minor used to retain two witness rows. -/
def pairCompressed (G : (B ⊕ Unit → D) → K) (x y : B → D)
    (a : (D × D) ⊕ Unit → D) : K :=
  G (a ∘ pairCompressionMap x y)

@[simp] theorem pairCompressed_first_row (G : (B ⊕ Unit → D) → K)
    (x y : B → D) :
    row (pairCompressed G x y) Prod.fst = row G x := by
  funext z
  unfold row pairCompressed
  congr 1
  funext i
  cases i <;> rfl

@[simp] theorem pairCompressed_second_row (G : (B ⊕ Unit → D) → K)
    (x y : B → D) :
    row (pairCompressed G x y) Prod.snd = row G y := by
  funext z
  unfold row pairCompressed
  congr 1
  funext i
  cases i <;> rfl

/-- The compressed minor is still generated by an actual finite instance. -/
theorem generated_pairCompressed [CommSemiring K] [Fintype D]
    {G : (B ⊕ Unit → D) → K} (hG : Instance.Generated L G) (x y : B → D) :
    Instance.Generated L (pairCompressed G x y) :=
  Instance.generated_diagonal_minor hG (pairCompressionMap x y)

/-- The number of external variables in the construction is exactly the paper's
bound. Unused pairs correspond to legal isolated variables. -/
theorem pairCompression_card [Fintype D] :
    Fintype.card ((D × D) ⊕ Unit) = Fintype.card D ^ 2 + 1 := by
  simp [pow_two]

/-- Any predicate of the two actual rows is preserved entry-for-entry by the
compression, including after applying one common entrywise purification map. -/
theorem pairCompressed_preserves_row_predicate
    (G : (B ⊕ Unit → D) → K) (x y : B → D)
    (P : (D → K) → (D → K) → Prop) :
    P (row (pairCompressed G x y) Prod.fst) (row (pairCompressed G x y) Prod.snd) ↔
      P (row G x) (row G y) := by simp

end ComplexCSP
