import ComplexCSP.Structure.WeightedMaltsevSuffix

/-! # A concrete immutable-context layer constructor

All variable-arity evaluation calls execute the original CSP product and the
already materialized suffix layers. The correctness invariant supplies literal
prefix marginals, so later machine compilation needs no evaluator oracle.
-/
namespace ComplexCSP.WeightedMaltsev
open MaltsevRelations MaltsevWitness ComplexityWitnessEncoding
variable {K : Type} [Field K] [DecidableEq K] {d s : ℕ}

omit [DecidableEq K] in
/-- Each literal prefix marginal is generated by the original finite language. -/
theorem generated_prefixMarginal (L : Language (Fin d) K (Fin s))
    (g : ComplexityCSPCode.Code) (hg : ComplexityCSPCode.Valid L g)
    (k : ℕ) (hk : k ≤ g.vertices) :
    Instance.Generated L (ComplexityCSPMarginalBounds.marginal L g hk) := by
  have aux : ∀ (fuel k : ℕ) (he : k + fuel = g.vertices),
      Instance.Generated L (ComplexityCSPMarginalBounds.marginal L g (by omega : k ≤ g.vertices)) := by
    intro fuel
    induction fuel with
    | zero =>
      intro k he
      have hk' : k = g.vertices := by omega
      subst k
      have heq : ComplexityCSPMarginalBounds.marginal L g (by omega) = ComplexityCSPCode.eval L g := by
        funext x
        exact ComplexityCSPMarginalBounds.marginal_full L g x
      rw [heq]
      exact raw_assignment_generated L g hg
    | succ fuel ih =>
      intro k he
      have hnext := ih (k+1) (by omega)
      have hmarg := generated_marginal _ hnext
      have heq : marginal (ComplexityCSPMarginalBounds.marginal L g (by omega : k+1 ≤ g.vertices)) =
          ComplexityCSPMarginalBounds.marginal L g (by omega : k ≤ g.vertices) := by
        funext x
        exact (ComplexityCSPMarginalBounds.marginal_succ L g _ _ x).symm
      rwa [heq] at hmarg
  exact aux (g.vertices-k) k (Nat.add_sub_of_le hk)

/-- Concrete callback/context recursion. The only persistent inputs are the
literal instance, stored witness table, and already materialized raw layers. -/
def compileContextLayers (L : Language (Fin d) K (Fin s)) (m : Operation (Fin d))
    (defaultValue : Fin d) (g : ComplexityCSPCode.Code) :
    {n : ℕ} → StoredCode d n → List (ComplexityWeightedLayers.Layer K) → List (ComplexityWeightedLayers.Layer K)
  | 0, _, layers => layers
  | _ + 1, W, layers =>
    let evaluate := fun x => ComplexityWeightedLayers.execute (fun a b c => m (a,b,c)) L g (word x) layers
    let layer := buildLayer m W.toCode evaluate defaultValue
    compileContextLayers L m defaultValue g (marginalSupportCode m layer) (encodeLayer layer :: layers)

section PositiveDomain
variable [NeZero d]

/-- Every stage in the actual context recursion preserves the exact raw
ComputeF marginal invariant and the actually constructed support witness. -/
theorem compileContextLayers_correct (L : Language (Fin d) K (Fin s)) (σ : K →+* ℂ)
    {m : Operation (Fin d)} (hm : IsMaltsev m)
    (hs : CommonPolymorphism (generatedSupports (L.mapValues σ)) m)
    (hrow : ∀ (n : ℕ), 0 < n → ∀ (G : (Fin (n+1) → Fin d) → ℂ),
      Instance.Generated (L.mapValues σ) G → Preserves m (RowTypes.omegaRelation G).tuples)
    (defaultValue : Fin d) (g : ComplexityCSPCode.Code) (hg : ComplexityCSPCode.Valid L g)
    (n : ℕ) (hn : n ≤ g.vertices) (W : StoredCode d n)
    (hW : Correct W.toCode {x | ComplexityCSPMarginalBounds.marginal L g hn x ≠ 0})
    (layers : List (ComplexityWeightedLayers.Layer K)) (hrep : RepresentsMarginal L m g hn layers) :
    ComplexityWeightedLayers.execute (fun a b c => m (a,b,c)) L g []
      (compileContextLayers L m defaultValue g W layers) = ComplexityCSPCode.partition L g := by
  induction n generalizing layers with
  | zero =>
    have h := hrep (Vector.ofFn Fin.elim0)
    simpa [compileContextLayers,word,ComplexityCSPMarginalBounds.marginal_empty] using h
  | succ n ih =>
    let G := ComplexityCSPMarginalBounds.marginal L g hn
    have hG : Instance.Generated L G := generated_prefixMarginal L g hg (n+1) hn
    obtain ⟨hR,hTP,hclasses⟩ := embedded_row_hypotheses L σ hm hrow G hG
    let evaluate := fun x : Tuple (Fin d) (n+1) => ComplexityWeightedLayers.execute (fun a b c => m (a,b,c)) L g (word x) layers
    let layer := buildLayer m W.toCode evaluate defaultValue
    have hv : ValidLayer G layer := buildLayer_correct hm G hW hR hTP hclasses evaluate hrep defaultValue
    have heq : marginal G = ComplexityCSPMarginalBounds.marginal L g (by omega : n ≤ g.vertices) := by
      funext x
      exact (ComplexityCSPMarginalBounds.marginal_succ L g _ hn x).symm
    have hpres := embedded_support_preserves L σ hs (marginal G) (generated_marginal G hG)
    have hnext := marginalSupportCode_correct hm G layer hv hclasses hpres
    rw [heq] at hnext
    have hr := representsMarginal_prepend L hm g (by omega) hn layers hrep layer hv hclasses
    exact ih (by omega) (marginalSupportCode m layer) hnext (encodeLayer layer::layers) hr

/-- The fully concrete context constructor, initialized by the literal original
support compiler. It carries no supplied table-evaluation function. -/
def compileRawContextLayers (L : Language (Fin d) K (Fin s)) (m : Operation (Fin d))
    (defaultValue : Fin d) (g : ComplexityCSPCode.Code) (hg : ComplexityCSPCode.Valid L g) :
    List (ComplexityWeightedLayers.Layer K) :=
  compileContextLayers L m defaultValue g (rawSupportWitness L m defaultValue g hg) []

/-- Genuine global BO supplies one common operation for the entire concrete
context-layer evaluator. Machine compilation of the constructor is separate. -/
theorem jointBO_context_execution [Nonempty (Fin d)] (L : Language (Fin d) K (Fin s)) (σ : K →+* ℂ)
    (hAlg : ∀ i a, IsAlgebraic ℚ ((L.mapValues σ).value i a)) (hBO : JointBO (L.mapValues σ))
    (defaultValue : Fin d) :
    ∃ m : Operation (Fin d), IsMaltsev m ∧
      ∀ (g : ComplexityCSPCode.Code) (hg : ComplexityCSPCode.Valid L g),
        ComplexityWeightedLayers.execute (fun a b c => m (a,b,c)) L g []
          (compileRawContextLayers L m defaultValue g hg) = ComplexityCSPCode.partition L g := by
  obtain ⟨m,hm,hs,hrow⟩ := RowEquivalenceRealization.common_support_and_row_maltsev (L.mapValues σ) hAlg hBO
  refine ⟨m,hm,?_⟩
  intro g hg
  have htables : ∀ i, Preserves m {x | L.value i x ≠ 0} := by
    intro i
    exact embedded_support_preserves L σ hs (L.value i) (language_value_generated L i)
  have hW := rawSupportWitness_correct L hm htables defaultValue g hg
  have heq : ComplexityCSPMarginalBounds.marginal L g le_rfl = ComplexityCSPCode.eval L g := by
    funext x
    exact ComplexityCSPMarginalBounds.marginal_full L g x
  apply compileContextLayers_correct L σ hm hs hrow defaultValue g hg g.vertices le_rfl
    (rawSupportWitness L m defaultValue g hg)
  · rwa [heq]
  · exact representsMarginal_empty L m g hg

end PositiveDomain
end ComplexCSP.WeightedMaltsev
